package awsglue

import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
)

// Example:
//   glue.NewDatabase(this, jsii.String("MyDatabase"), &DatabaseProps{
//   	DatabaseName: jsii.String("my_database"),
//   	Description: jsii.String("my_database_description"),
//   })
//
type DatabaseProps struct {
	// The catalog in which the database will be placed.
	// Default: The default, account-wide catalog.
	//
	Catalog ICatalog `field:"optional" json:"catalog" yaml:"catalog"`
	// The name of the database.
	// Default: - generated by CDK.
	//
	DatabaseName *string `field:"optional" json:"databaseName" yaml:"databaseName"`
	// A description of the database.
	// Default: - no database description.
	//
	Description *string `field:"optional" json:"description" yaml:"description"`
	// The location of the database (for example, an HDFS path).
	// See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-database-databaseinput.html
	//
	// Default: undefined. This field is optional in AWS::Glue::Database DatabaseInput
	//
	LocationUri *string `field:"optional" json:"locationUri" yaml:"locationUri"`
	// Policy to apply when the database is removed from the stack.
	//
	// A database is a container for tables and their metadata, so it is retained
	// by default to avoid accidental data loss when it is removed from a stack.
	// Default: RemovalPolicy.RETAIN
	//
	RemovalPolicy awscdk.RemovalPolicy `field:"optional" json:"removalPolicy" yaml:"removalPolicy"`
}

