package awsglue

import (
	_init_ "github.com/aws/aws-cdk-go/awscdk/v2/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awscloudwatch"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsevents"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsglue"
	"github.com/aws/constructs-go/constructs/v10"
)

// Python Spark Streaming Jobs class.
//
// A Streaming job is similar to an ETL job, except that it performs ETL on data streams
// using the Apache Spark Structured Streaming framework.
// These jobs run on Python 3.
//
// Similar to ETL jobs, streaming job supports Scala and Python languages. Streaming jobs
// default to the `G_1X` worker type and Glue version 4.0, both of which developers can
// override with any supported `WorkerType` or `GlueVersion`.
// We will enable --enable-metrics, --enable-continuous-cloudwatch-log. The Spark UI
// (--enable-spark-ui) is off by default; enable it by setting the `sparkUI` prop.
//
// Example:
//   import cdk "github.com/aws/aws-cdk-go/awscdk"
//   import iam "github.com/aws/aws-cdk-go/awscdk"
//   var stack Stack
//   var role IRole
//   var script Code
//
//   glue.NewPySparkStreamingJob(stack, jsii.String("ImportedJob"), &PySparkStreamingJobProps{
//   	Role: Role,
//   	Script: Script,
//   })
//
type PySparkStreamingJob interface {
	SparkJob
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	Env() *interfaces.ResourceEnvironment
	// The principal to grant permissions to.
	GrantPrincipal() awsiam.IPrincipal
	// The ARN of the job.
	JobArn() *string
	// The name of the job.
	JobName() *string
	// A reference to this Job resource, for use with the generated L1 ref interface.
	JobRef() *interfacesawsglue.JobReference
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The IAM role Glue assumes to run this job.
	Role() awsiam.IRole
	// The Spark UI logs location if Spark UI monitoring and debugging is enabled.
	// See: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-glue-arguments.html
	//
	SparkUILoggingLocation() *SparkUILoggingLocation
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// Override the cross-stack reference strength for this resource.
	//
	// When set, any cross-stack reference to this resource will use the specified
	// mechanism instead of the global default determined by the
	// `@aws-cdk/core:defaultCrossStackReferences` context key. This is useful for
	// selectively weakening specific references to avoid the "deadly embrace" problem
	// without changing the app-wide default.
	ApplyCrossStackReferenceStrength(strength awscdk.ReferenceStrength)
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Returns the job arn.
	BuildJobArn(scope constructs.Construct, jobName *string) *string
	CodeS3ObjectUrl(code Code) *string
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Merge the customer-supplied `defaultArguments` with the arguments this construct manages.
	//
	// The construct owns every argument it emits — whether the value comes from a dedicated typed
	// prop (e.g. `continuousLogging`, `enableMetrics`, `sparkUI`) or from the job class itself
	// (e.g. `--job-language`). Those arguments, plus the arguments Glue reserves for its own use,
	// MUST be configured through their dedicated props rather than the untyped `defaultArguments`
	// map, so there is exactly one way to express each intent. Passing such a key through
	// `defaultArguments` therefore throws instead of silently winning or being silently dropped.
	//
	// A managed key whose supplied value is identical to the construct's value is not contradictory,
	// so it is allowed rather than rejected (auto-correcting config is preferred over errors).
	// Glue-reserved keys are never emitted by the construct, so there is no value to reconcile and
	// they always throw.
	//
	// The reserved set is `_managedArgumentKeys` — every key the construct declared through
	// {@link setManagedArgument}, whether or not a value was emitted for it. It is deliberately NOT
	// derived from the keys that carry a value: a typed prop that turns a feature *off* (e.g.
	// `enableMetrics: false`) emits no value but still reserves its key, so `defaultArguments` cannot
	// silently re-enable it.
	//
	// Conflict detection relies on string equality of the argument keys, which cannot see through
	// unresolved tokens (e.g. a key produced by `CfnJson` that only resolves at deploy time). If a
	// key is a token, the check is skipped for that key and a synthesis-time warning is emitted, so
	// the (rare) case where a token key resolves to a managed argument at deploy time — in which the
	// construct-managed value would silently take precedence — is surfaced rather than hidden.
	// See: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-glue-arguments.html
	//
	MergeDefaultArguments(defaultArguments *map[string]*string) *map[string]*string
	// Create a CloudWatch metric.
	// See: https://docs.aws.amazon.com/glue/latest/dg/monitoring-awsglue-with-cloudwatch-metrics.html
	//
	Metric(metricName *string, type_ MetricType, props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Return a CloudWatch Metric indicating job failure.
	//
	// This metric is based on the Rule returned by no-args onFailure() call.
	MetricFailure(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Return a CloudWatch Metric indicating job success.
	//
	// This metric is based on the Rule returned by no-args onSuccess() call.
	MetricSuccess(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Return a CloudWatch Metric indicating job timeout.
	//
	// This metric is based on the Rule returned by no-args onTimeout() call.
	MetricTimeout(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Register the arguments this construct manages for a Spark job.
	//
	// These are owned by the construct
	// (derived from typed props). Each key is declared via {@link setManagedArgument} whether or not
	// the current configuration emits a value, so a disabled feature (e.g. `enableMetrics: false`)
	// cannot be silently re-enabled through `defaultArguments`.
	NonExecutableCommonArguments(props *SparkJobProps)
	// Create a CloudWatch Event Rule for this Glue Job when it's in a given state.
	// See: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html#glue-event-types
	//
	OnEvent(id *string, options *awsevents.OnEventOptions) awsevents.Rule
	// Return a CloudWatch Event Rule matching FAILED state.
	OnFailure(id *string, options *awsevents.OnEventOptions) awsevents.Rule
	// Create a CloudWatch Event Rule for the transition into the input jobState.
	OnStateChange(id *string, jobState JobState, options *awsevents.OnEventOptions) awsevents.Rule
	// Create a CloudWatch Event Rule matching JobState.SUCCEEDED.
	OnSuccess(id *string, options *awsevents.OnEventOptions) awsevents.Rule
	// Return a CloudWatch Event Rule matching TIMEOUT state.
	OnTimeout(id *string, options *awsevents.OnEventOptions) awsevents.Rule
	// Declare `key` as construct-managed and, when `value` is defined, emit it into the job's arguments.
	//
	// This is the single sink for every argument a job construct derives from its typed props (or
	// from the job class itself). Call it once per managed key, passing `undefined` as the value when
	// the corresponding feature is turned off or unset — the key is still reserved from
	// `defaultArguments` either way, so a disabled feature cannot be re-enabled through the escape
	// hatch. There is deliberately no other way for a subclass to emit a managed argument, so the
	// reserved set can never drift from what is emitted.
	SetManagedArgument(key *string, value *string)
	// Register (and, when enabled, emit) the continuous-logging arguments this job manages.
	//
	// All five continuous-logging keys are reserved on every job type regardless of configuration:
	// they are always registered through {@link setManagedArgument}, and carry a value only when
	// logging is enabled. This keeps `defaultArguments` from re-enabling logging a user turned off.
	SetupContinuousLogging(role awsiam.IRole, props *ContinuousLoggingProps, securityConfiguration ISecurityConfiguration)
	// Register the arguments for extra {@link Code}-related properties.
	SetupExtraCodeArguments(props *SparkExtraCodeProps)
	// Returns a string representation of this construct.
	ToString() *string
	// Applies one or more mixins to this construct.
	//
	// Mixins are applied in order. The list of constructs is captured at the
	// start of the call, so constructs added by a mixin will not be visited.
	// Use multiple `with()` calls if subsequent mixins should apply to added
	// constructs.
	With(mixins ...constructs.IMixin) constructs.IConstruct
}

// The jsii proxy struct for PySparkStreamingJob
type jsiiProxy_PySparkStreamingJob struct {
	jsiiProxy_SparkJob
}

func (j *jsiiProxy_PySparkStreamingJob) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PySparkStreamingJob) GrantPrincipal() awsiam.IPrincipal {
	var returns awsiam.IPrincipal
	_jsii_.Get(
		j,
		"grantPrincipal",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PySparkStreamingJob) JobArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"jobArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PySparkStreamingJob) JobName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"jobName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PySparkStreamingJob) JobRef() *interfacesawsglue.JobReference {
	var returns *interfacesawsglue.JobReference
	_jsii_.Get(
		j,
		"jobRef",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PySparkStreamingJob) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PySparkStreamingJob) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PySparkStreamingJob) Role() awsiam.IRole {
	var returns awsiam.IRole
	_jsii_.Get(
		j,
		"role",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PySparkStreamingJob) SparkUILoggingLocation() *SparkUILoggingLocation {
	var returns *SparkUILoggingLocation
	_jsii_.Get(
		j,
		"sparkUILoggingLocation",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PySparkStreamingJob) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// PySparkStreamingJob constructor.
func NewPySparkStreamingJob(scope constructs.Construct, id *string, props *PySparkStreamingJobProps) PySparkStreamingJob {
	_init_.Initialize()

	if err := validateNewPySparkStreamingJobParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_PySparkStreamingJob{}

	_jsii_.Create(
		"aws-cdk-lib.aws_glue.PySparkStreamingJob",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// PySparkStreamingJob constructor.
func NewPySparkStreamingJob_Override(p PySparkStreamingJob, scope constructs.Construct, id *string, props *PySparkStreamingJobProps) {
	_init_.Initialize()

	_jsii_.Create(
		"aws-cdk-lib.aws_glue.PySparkStreamingJob",
		[]interface{}{scope, id, props},
		p,
	)
}

// Identifies an existing Glue Job from a subset of attributes that can be referenced from within another Stack or Construct.
func PySparkStreamingJob_FromJobAttributes(scope constructs.Construct, id *string, attrs *JobAttributes) IJob {
	_init_.Initialize()

	if err := validatePySparkStreamingJob_FromJobAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IJob

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_glue.PySparkStreamingJob",
		"fromJobAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
func PySparkStreamingJob_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validatePySparkStreamingJob_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_glue.PySparkStreamingJob",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func PySparkStreamingJob_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validatePySparkStreamingJob_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_glue.PySparkStreamingJob",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func PySparkStreamingJob_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validatePySparkStreamingJob_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_glue.PySparkStreamingJob",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func PySparkStreamingJob_PROPERTY_INJECTION_ID() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"aws-cdk-lib.aws_glue.PySparkStreamingJob",
		"PROPERTY_INJECTION_ID",
		&returns,
	)
	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) ApplyCrossStackReferenceStrength(strength awscdk.ReferenceStrength) {
	if err := p.validateApplyCrossStackReferenceStrengthParameters(strength); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		p,
		"applyCrossStackReferenceStrength",
		[]interface{}{strength},
	)
}

func (p *jsiiProxy_PySparkStreamingJob) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := p.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		p,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (p *jsiiProxy_PySparkStreamingJob) BuildJobArn(scope constructs.Construct, jobName *string) *string {
	if err := p.validateBuildJobArnParameters(scope, jobName); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		p,
		"buildJobArn",
		[]interface{}{scope, jobName},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) CodeS3ObjectUrl(code Code) *string {
	if err := p.validateCodeS3ObjectUrlParameters(code); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		p,
		"codeS3ObjectUrl",
		[]interface{}{code},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		p,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := p.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		p,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) GetResourceNameAttribute(nameAttr *string) *string {
	if err := p.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		p,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) MergeDefaultArguments(defaultArguments *map[string]*string) *map[string]*string {
	var returns *map[string]*string

	_jsii_.Invoke(
		p,
		"mergeDefaultArguments",
		[]interface{}{defaultArguments},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) Metric(metricName *string, type_ MetricType, props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := p.validateMetricParameters(metricName, type_, props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		p,
		"metric",
		[]interface{}{metricName, type_, props},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) MetricFailure(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := p.validateMetricFailureParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		p,
		"metricFailure",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) MetricSuccess(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := p.validateMetricSuccessParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		p,
		"metricSuccess",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) MetricTimeout(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := p.validateMetricTimeoutParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		p,
		"metricTimeout",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) NonExecutableCommonArguments(props *SparkJobProps) {
	if err := p.validateNonExecutableCommonArgumentsParameters(props); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		p,
		"nonExecutableCommonArguments",
		[]interface{}{props},
	)
}

func (p *jsiiProxy_PySparkStreamingJob) OnEvent(id *string, options *awsevents.OnEventOptions) awsevents.Rule {
	if err := p.validateOnEventParameters(id, options); err != nil {
		panic(err)
	}
	var returns awsevents.Rule

	_jsii_.Invoke(
		p,
		"onEvent",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) OnFailure(id *string, options *awsevents.OnEventOptions) awsevents.Rule {
	if err := p.validateOnFailureParameters(id, options); err != nil {
		panic(err)
	}
	var returns awsevents.Rule

	_jsii_.Invoke(
		p,
		"onFailure",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) OnStateChange(id *string, jobState JobState, options *awsevents.OnEventOptions) awsevents.Rule {
	if err := p.validateOnStateChangeParameters(id, jobState, options); err != nil {
		panic(err)
	}
	var returns awsevents.Rule

	_jsii_.Invoke(
		p,
		"onStateChange",
		[]interface{}{id, jobState, options},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) OnSuccess(id *string, options *awsevents.OnEventOptions) awsevents.Rule {
	if err := p.validateOnSuccessParameters(id, options); err != nil {
		panic(err)
	}
	var returns awsevents.Rule

	_jsii_.Invoke(
		p,
		"onSuccess",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) OnTimeout(id *string, options *awsevents.OnEventOptions) awsevents.Rule {
	if err := p.validateOnTimeoutParameters(id, options); err != nil {
		panic(err)
	}
	var returns awsevents.Rule

	_jsii_.Invoke(
		p,
		"onTimeout",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) SetManagedArgument(key *string, value *string) {
	if err := p.validateSetManagedArgumentParameters(key); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		p,
		"setManagedArgument",
		[]interface{}{key, value},
	)
}

func (p *jsiiProxy_PySparkStreamingJob) SetupContinuousLogging(role awsiam.IRole, props *ContinuousLoggingProps, securityConfiguration ISecurityConfiguration) {
	if err := p.validateSetupContinuousLoggingParameters(role, props); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		p,
		"setupContinuousLogging",
		[]interface{}{role, props, securityConfiguration},
	)
}

func (p *jsiiProxy_PySparkStreamingJob) SetupExtraCodeArguments(props *SparkExtraCodeProps) {
	if err := p.validateSetupExtraCodeArgumentsParameters(props); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		p,
		"setupExtraCodeArguments",
		[]interface{}{props},
	)
}

func (p *jsiiProxy_PySparkStreamingJob) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		p,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PySparkStreamingJob) With(mixins ...constructs.IMixin) constructs.IConstruct {
	args := []interface{}{}
	for _, a := range mixins {
		args = append(args, a)
	}

	var returns constructs.IConstruct

	_jsii_.Invoke(
		p,
		"with",
		args,
		&returns,
	)

	return returns
}

